# Generated by wor-agentic-architect on {{generated_at}}.
# This subsystem is independent of the AiAgentArchitect parent.
# Edit by re-running the workflow.

aiagent_architect_version: {{aiagent_architect_version}}
generated_at: {{generated_at}}
generated_by: wor-agentic-architect
project_name: {{project_name}}
mode: {{mode}}

# Platforms this subsystem targets. Sync scripts (sync-dual.sh, build-codex.py)
# read this list and skip outputs for platforms not present.
platforms:
{{#each platforms}}
  - {{this}}
{{/each}}

# Layers embedded in this subsystem. The orchestrator populates this via
# ski-layer-embed for each layer activated for this subsystem.
layers_root:
{{#each layers}}
  {{name}}:
    enabled: true
    version: {{version}}
    embedded_at: {{embedded_at}}
{{/each}}

# Layers default for any nested subsystem this one might generate (rare).
layers_subsystem_defaults: {}
